-- Creación de vistas globales para todas las localidades

-- Vista global para empleados
CREATE VIEW EmpleadoView AS 
SELECT * FROM EMPLEADO1
UNION
SELECT * FROM EMPLEADO2
UNION
SELECT * FROM EMPLEADO3
UNION
SELECT * FROM EMPLEADO4;

-- Vista global para proveedores
CREATE VIEW ProveedorView AS 
SELECT * FROM PROVEEDOR1
UNION
SELECT * FROM PROVEEDOR2
UNION
SELECT * FROM PROVEEDOR3
UNION
SELECT * FROM PROVEEDOR4;

-- Vista global para artículos
CREATE VIEW ArticuloView AS 
SELECT * FROM ARTICULO1
UNION
SELECT * FROM ARTICULO2
UNION
SELECT * FROM ARTICULO3
UNION
SELECT * FROM ARTICULO4;

-- Vista global para hoteles
CREATE VIEW HotelView AS 
SELECT * FROM HOTEL1
UNION
SELECT * FROM HOTEL2
UNION
SELECT * FROM HOTEL3
UNION
SELECT * FROM HOTEL4;

-- Vista global para clientes
CREATE VIEW ClienteView AS 
SELECT * FROM CLIENTE1
UNION
SELECT * FROM CLIENTE2
UNION
SELECT * FROM CLIENTE3
UNION
SELECT * FROM CLIENTE4;

-- Vista global para reservas
CREATE VIEW ReservaView AS 
SELECT * FROM RESERVA1
UNION
SELECT * FROM RESERVA2
UNION
SELECT * FROM RESERVA3
UNION
SELECT * FROM RESERVA4;

-- Vista global para asignaciones
CREATE VIEW AsignacionView AS 
SELECT * FROM ASIGNACION1
UNION
SELECT * FROM ASIGNACION2
UNION
SELECT * FROM ASIGNACION3
UNION
SELECT * FROM ASIGNACION4;

-- Vista global para suministros
CREATE VIEW SuministroView AS 
SELECT * FROM SUMINISTRO1
UNION
SELECT * FROM SUMINISTRO2
UNION
SELECT * FROM SUMINISTRO3
UNION
SELECT * FROM SUMINISTRO4;
